package org.ciroque
import scala.collection.immutable

object AoC2 extends Data with App {
  println(s"Checksum: ${Solution.calculateChecksum(boxIds)}")
  println(s"Prototype Id: ${Solution.findCommonLetters(boxIds)}")
}

object Solution {
  def calculateChecksum(boxIds: List[String]): Int = {
    def findTwoAndThreeCharacterCounts(boxId: String): Map[Char, Int] = {
      boxId
        .groupBy(_.toChar)
        .map{ p => (p._1, p._2.length)}
        .filter(p => p._2 > 1 && p._2 < 4)
    }

    val allCounts =  boxIds.map(findTwoAndThreeCharacterCounts(_))

    val results = allCounts.foldLeft((0, 0)) {
      case ((twos: Int, threes: Int), counts: Map[Char, Int]) =>
        val two = if(counts.count(_._2 == 2) > 0) 1 else 0
        val three = if(counts.count(_._2 == 3) > 0) 1 else 0
        ((twos + two, threes + three))
    }

    results._1 * results._2
  }

  def findCommonLetters(boxIds: List[String]): String = {
    def compareStrings(left: String, right: String): Int = {
      (left zip right) count {
        case (l, r) => l != r
      }
    }

    val candidates = boxIds
      .map(s => (s, boxIds.filter(p => compareStrings(s, p) == 1)))
      .filter(candidate => candidate._2.length > 0)

    // NOTE: This does not remove the character, that part needs to be done manually at the moment, but it is late (early..)

    println(s"... $candidates")

    "ABCD"
  }
}

trait Data {
  lazy val boxIds = List(
    "bvhfawknyoqsudzrpgslecmtkj",
    "bpufawcnyoqxldzrpgsleimtkj",
    "bvhfawcnyoqxqdzrplsleimtkf",
    "bvhoagcnyoqxudzrpgsleixtkj",
    "bxvfgwcnyoqxudzrpgsleimtkj",
    "bvqfawcngoqxudzrpgsleiktkj",
    "bvhfawcnmoqxuyzrpgsleimtkp",
    "bvheawcnyomxsdzrpgsleimtkj",
    "bcdfawcnyoqxudzrpgsyeimtkj",
    "bvhpawcnyoqxudzrpgsteimtkz",
    "bxhfawcnyozxudzrpgsleimtoj",
    "bvhfdwcnyozxudzrposleimtkj",
    "bvpfawcnyotxudzrpgsleimtkq",
    "bvhfpwccyoqxudzrpgslkimtkj",
    "bvhfawcnyoqxudirpgsreimtsj",
    "bvhfawcnyoqxudzppgbleemtkj",
    "bvhzawcnyoqxudqrpgslvimtkj",
    "bvhfawclyoqxudirpgsleimtka",
    "bvhgawfnyoqxudzrpguleimtkj",
    "bvhfazcnytqxudzrpgslvimtkj",
    "bvhfawcnygxxudzrpgjleimtkj",
    "bxhfawcnyoqxudzipgsleimtxj",
    "bvhptwcnyoqxudzrpgsleimtmj",
    "bzhfawcgyooxudzrpgsleimtkj",
    "bvhjlwcnyokxudzrpgsleimtkj",
    "bvhfawcnyoqxudbrmgslesmtkj",
    "bvhfawcnysixudzwpgsleimtkj",
    "bvhflwcnymqxxdzrpgsleimtkj",
    "bvifawcnyoyxudzrpgsleimtvj",
    "bvhfawcnyofxudlrpgsheimtkj",
    "bvhbawcmyoqxudzrpggleimtkj",
    "bhhxgwcnyoqxudzrpgsleimtkj",
    "bvhfawgnyoqxbdzrpgsleimfkj",
    "bvhfawcnyoqxudcrngsleimykj",
    "bvhfawcnyofxudzrpgslebgtkj",
    "bvhfaocnybqxudzapgsleimtkj",
    "bvhxawcnyodxudzrpfsleimtkj",
    "bchfawcnyoqxudrrtgsleimtkj",
    "bvhfawcqyoqxudzdpgsltimtkj",
    "bvhfawknyoqxudzrpnsleimtbj",
    "cihfawcnyoqxudirpgsleimtkj",
    "bvlfawpnyoqxudzrpgslgimtkj",
    "bulfawcnyoqbudzrpgsleimtkj",
    "bvhfajcnyoqkudzrpgsoeimtkj",
    "bvhrakcnyoqxudzrpgsleimjkj",
    "bvbftwcnyoqxuvzrpgsleimtkj",
    "bvhfhwcnyoqxudzrpgslelmtbj",
    "bvhyawcntoqxudzrpgsleimtuj",
    "xvhuawcnyoqxuqzrpgsleimtkj",
    "pvhfawcnyoqxudzdpglleimtkj",
    "bvhfawsnyoqxudzrpgvlefmtkj",
    "bvhfawcnyoqxudzrpgepeiwtkj",
    "bvhfawcnyoqxudzrphsleittkr",
    "dvhfawcnyoqxudzrpkslzimtkj",
    "bvhfawpnyoqxudzrpgmlcimtkj",
    "bvhsawcnyzqxudzrpgsaeimtkj",
    "bdhfawcnyoqxudzrpasleiwtkj",
    "bvhfawbnyoqxpdbrpgsleimtkj",
    "mvhfawwnyoqxujzrpgsleimtkj",
    "bvafawcnyoyxudzrpgsleidtkj",
    "bvhyawcnyoqxudztpgzleimtkj",
    "besfawcnyoqxudzrpgsleimdkj",
    "bvhfawcnyoqxudrrpgsjeimjkj",
    "xvhfkwcnyoqxudzcpgsleimtkj",
    "bvhfawcnyeqdudzrpgzleimtkj",
    "bvhfuwcnybqxudzrpgsleimttj",
    "lvhfawcnyoqhudzdpgsleimtkj",
    "bvhfawcnyoqxudzrpgslevwtnj",
    "bvhfadcnzoqxxdzrpgsleimtkj",
    "bvsfawcnyoqxpdzrpgileimtkj",
    "bzhfaycnyoqxudzrpgsxeimtkj",
    "bwhfdwcnyoqxudzrpgsleimtkz",
    "bvhfawcnyoqxudzrpgsjlimtkm",
    "bvhfawcnyoqxudsrwgsleimtlj",
    "bbhfalynyoqxudzrpgsleimtkj",
    "bvhfawcnyeqxudzrpglleimtkr",
    "bvhfawnnboqxurzrpgsleimtkj",
    "yvhfawcnyoqxudzrpgslzimtpj",
    "bvhfjwcnyoqxqdxrpgsleimtkj",
    "bthfawcnyoqfudzrpgslhimtkj",
    "bvhfawchuoqxudzqpgsleimtkj",
    "bvhfawcndoqxudzrugsleimrkj",
    "bvhfawcnnoqxjdzrpgsleidtkj",
    "bvhpawcnyoqkudzrpgsleimtzj",
    "bvhfaiinyoqxudzopgsleimtkj",
    "bvhfawcnyxqxuizrigsleimtkj",
    "bvnfawcnyoqxudzqpgsleimbkj",
    "bvnfawcnyoeyudzrpgsleimtkj",
    "bvhfawcnyoqxudarpgsieimtoj",
    "bthcawcnyoqxudlrpgsleimtkj",
    "bvhfnwcnyozxudzrpgsleomtkj",
    "bpwfawcnyoqxudzrpgskeimtkj",
    "bvhfapcnyoqxudnrpgsxeimtkj",
    "bvhfdwcnyoqxubzrxgsleimtkj",
    "fvhfawcnyoqxjdzrpgsleirtkj",
    "bvhfawcneoqxudzrvzsleimtkj",
    "bvhaawcnyoqxudzrpgsleimtex",
    "bvhfawcnyojxudvrpgsleimckj",
    "bvlfawcnyoqxddzrpgsleimtko",
    "bvhfawclfoqxudzrpgsleiktkj",
    "bvhfawciyobxudzrpgkleimtkj",
    "bvhfpwcnyoqxudzrpgsqeimtkd",
    "bvhyawcnyyqxudzrkgsleimtkj",
    "bvhfawcncoqxudzrphsaeimtkj",
    "bvhfawmnyoqxudzrpgifeimtkj",
    "bvhfawcjyoqxudzjpgszeimtkj",
    "bohfawcnwoqxudzrpgsleimwkj",
    "bvhfaucnyoqxudzrpgfluimtkj",
    "bvhfawlnyoqgudzrpgwleimtkj",
    "bmhfawcnyoqxndzrpgsleymtkj",
    "bvhfawcngoqxudzrpzxleimtkj",
    "bihfawcnyoqxudrrpgsleimokj",
    "lvhfawcnylqxudzrpgsleintkj",
    "bvhfawcnyoqvugzrqgsleimtkj",
    "bvhfawcnyoqxudzgpgslqimtij",
    "bvhfawcnyoqludzrpgslnimtcj",
    "hvhfawcnyolxudzrpgsmeimtkj",
    "nvhfawcdkoqxudzrpgsleimtkj",
    "bvhfawcnyoqxkdzrggsneimtkj",
    "bvhfawnnyoqxudzrpgqleibtkj",
    "bvhfawyuyoqxudzrhgsleimtkj",
    "wvhfbwcnyoqxtdzrpgsleimtkj",
    "bvhfawcnyoqxedzzpgoleimtkj",
    "bvhfawcnioqxunzrpgsleimtnj",
    "bvhfawctyoqxudzrpgsldkmtkj",
    "bvhfawcnyonxudzrpgsleitpkj",
    "bvefawcnyoqaudzhpgsleimtkj",
    "bvhfawcnyxqxudzrpgslelmbkj",
    "bvhfamrnyoqxudzrpgsleimgkj",
    "bvhfaqcnyoqxudzrpgsaeimekj",
    "bvhfawcnyoqcidzrpgsleimvkj",
    "bvhfawcnnorxudzrpgsmeimtkj",
    "bvroawcnyoqxudzrpgsleiwtkj",
    "bvhfwwcnyoqxudzrpaslewmtkj",
    "bvsfawcnyoqxudzcpgszeimtkj",
    "bkhfmwcnyoqjudzrpgsleimtkj",
    "bvtfawcnyoqxudzrcgslecmtkj",
    "bvhfawcnypzxudzrpgsleimtkv",
    "bvhfawcnyoqzudzrfgtleimtkj",
    "bvhpawcnyoqxudhrpgsleimtko",
    "tvhfawcnyoqxudzxpfsleimtkj",
    "bvhfawccyofxudzrpqsleimtkj",
    "bvnfawtnyoqxuzzrpgsleimtkj",
    "bvhfamcnuwqxudzrpgsleimtkj",
    "bvhfawcfyoqxudjrpgsleimrkj",
    "bvhpalcnyoqxudzrpgslexmtkj",
    "bvhfawcnjsqxudzlpgsleimtkj",
    "bvhfafcnioqxydzrpgsleimtkj",
    "bvzfawcnyxqxudzgpgsleimtkj",
    "bvhzawcnyoqxudzrpgslewctkj",
    "bvhiawcnhoqrudzrpgsleimtkj",
    "bvhfawcnyoqxuszrggslenmtkj",
    "bvhfowcnyoqxudzrptseeimtkj",
    "behfawfnyoqxudzrpgsleimlkj",
    "lvhfawcnyoqxudsrpgvleimtkj",
    "bvhfawnnyaqxudzrpgsqeimtkj",
    "lvhfawcnfoqxvdzrpgsleimtkj",
    "svhxawcnyoqxudzrpqsleimtkj",
    "bvhfawqnfoqxudzrpgsleimkkj",
    "bvhfafcnyoqcudzrpgsleimtcj",
    "bvhfyfcntoqxudzrpgsleimtkj",
    "bvhfpwcnyoqxudzrpgsleimumj",
    "bvhfawccyoqxudzrqgrleimtkj",
    "bvhfawqnyoqxudzbpgsleimkkj",
    "bvhflwcnyoqxudzrpxsleemtkj",
    "bvhfawcnyoqxuezrpgslehrtkj",
    "bvhfawceyoqxudzrpgsleimswj",
    "bvhfawcncohgudzrpgsleimtkj",
    "bahfawcnyoqxgdzrpgsleamtkj",
    "yvhfawcnyoqxudzrppslrimtkj",
    "fvhfawcmyoqxudzrpgskeimtkj",
    "bvylawsnyoqxudzrpgsleimtkj",
    "bvhfswcnyyqxedzrpgsleimtkj",
    "fvrfawcnyoqxudzrpgzleimtkj",
    "bvhfawcnyoqxuvzrpgslermtks",
    "bvhkawccyoqxudzcpgsleimtkj",
    "bvhfaobnyoqxudzrprsleimtkj",
    "bvbfawcnyoqxudirpgsleimhkj",
    "bvhfawcnyoqxudzvpgsueimtgj",
    "bvhxawcnyoqxudzrpgsleimtgi",
    "svhfawcjyoqxuszrpgsleimtkj",
    "bvnfawcnyoeyudzrpgsldimtkj",
    "bvhfawcnyoqxuhzrpgsleimcki",
    "bvhfvwcnyoqxudzizgsleimtkj",
    "bvhfapznyohxudzrpgsleimtkj",
    "bvhfaelnyosxudzrpgsleimtkj",
    "xvhfawcnmoqxuhzrpgsleimtkj",
    "bjhfawcnyaqxutzrpgsleimtkj",
    "bvhfawcnyohxudzrpgslgnmtkj",
    "bvhfawcnyoqxudzrppsreimtkx",
    "fvhfapcnyoqyudzrpgsleimtkj",
    "qvhfafcnyoqxudorpgsleimtkj",
    "bvhfawcnyoqxedzrwgsleimtvj",
    "bvhfawgnyoqxudzupgqleimtkj",
    "bvhfowctyoqxudzrpgbleimtkj",
    "bvhwawcnyoqxudzapgslvimtkj",
    "bvhfadcnyoqxudzrugsleimtuj",
    "bvhfawcnyosxudzlpgsleamtkj",
    "bvhfawcnywqxuqzrpgsloimtkj",
    "bvhfawcnyoqxumzrpgvlfimtkj",
    "bvhfawcgyoqxbdzrpgsleomtkj",
    "bvhfahcnyoqwudzrfgsleimtkj",
    "gvbfawcnyrqxudzrpgsleimtkj",
    "svhfawcnyoqxudlrpgsleimtkx",
    "avhfafcnyoqxuhzrpgsleimtkj",
    "bvhfawcsyoqxuazrpgsleimtej",
    "bvofawcnyoqxudzrpgsteimtkf",
    "bvhfajcnyoqxudzqpgszeimtkj",
    "bvhfawcsyoqxudzrmgsleiktkj",
    "mvhfawcnyoqxudzrpgkluimtkj",
    "bvhfawcnhoqxudzrpgslwhmtkj",
    "bmhaawsnyoqxudzrpgsleimtkj",
    "bvhfawcnyoqxudzhpgsleimhyj",
    "bvhfxwcnyoqxsdzypgsleimtkj",
    "bvhpawcyyoqxuczrpgsleimtkj",
    "bvomawcnyovxudzrpgsleimtkj",
    "bvhfawcnjvqxudzrpgsleimtkt",
    "nvhfawcnyqqxudzrpgsleittkj",
    "bvhiawcnyzqxudzrpysleimtkj",
    "bvhdawcnyoqxukzrpgsleimtuj",
    "bvhfawcnyyxxudzrpgslzimtkj",
    "hvhfawcnyoqxudzupgslemmtkj",
    "byhfawknyoqxudzrpgsleimtkb",
    "bvhfawcnyoqxudzrpasleihakj",
    "bvafahcnyaqxudzrpgsleimtkj",
    "bkhfawcnyoqxudzrpgllepmtkj",
    "bghfawcnycqxuzzrpgsleimtkj",
    "bvhfawcnyoqxudzrbgeleimtkl",
    "bvhfascnyoqgudzrpgsveimtkj",
    "bvhfawnnyoqxudzrpgsleimtdl",
    "bvhqawcnyoqxudzrpgsleimgrj",
    "bvhsawdwyoqxudzrpgsleimtkj",
    "bvhfawcnyoqxudzrpgaleipttj",
    "bvhfawcnrlqxudzrbgsleimtkj",
    "bvhfdwcnyoqxudzqpcsleimtkj",
    "bvhfawcnyoqxudzopgslexmokj",
    "bvhfawcoyoqxudzrpghlewmtkj",
    "bvhfozcnykqxudzrpgsleimtkj",
    "bvhfawcnyoqxuvzrpgslrimtkr",
    "bvhfrncnyoqrudzrpgsleimtkj",
    "bvhfawcnyocxuizrpgslefmtkj",
    "bvhfawywyoqxudzrpgsleimxkj",
    "bvhfawcnyoqxugzrpgslrimtij",
    "bvtfawcnyoqxudzcpgsleimtfj",
    "bvhfawcnyoqxuzzspgsleimtkz",
    "bvhfawcnzoqxvdzrpgslsimtkj",
    "bvhfzwcnyoqxudzrpgslenmhkj",
    "bvhfkccnyoqxudzrpgzleimtkj",
    "bvhfawcnyoqzudzrpgslhimwkj",
    "bzhfawvnyooxudzrpgsleimtkj"
  )
}